name : GitHub_Actions 
on: 
   push: 
     branches: 
       -main
jobs: 
  build: 
      runs-on: ubuntu-latest 
      steps: 
         - name: Build
           run: echo "Building project ..."
  test:
       runs-on: ubuntu-latest 
       needs: build 
       steps: 
         - name: Run Tests  
           run: echo "Running tests ..."

  deploy: 
      runs-on: ubuntu-latest 
      needs: test 
      steps: 
        - name: Deploy to final stage 
          run: echo "Deploying project ..."  
      
